[channel]
generator = utipod
xmlbase = http://174.93.162.91:8080/UC-wPh48ip_s4P6guKziI7ag
title = "info@iccnc.org"
link = https://www.youtube.com/channel/UC-wPh48ip_s4P6guKziI7ag
description = "Islamic Cultural Center of Northern California (ICCNC) is an independent, non-profit, community-based, religious 501(c)(3) organization. ICCNC provides a dynamic space that cultivates an exchange of ideas about Islam through art, culture, and education programs.   \n\nMission: Our mission is to celebrate Islam through art, culture, and education.\n\nVision: Our vision is to achieve a more compassionate and just society by giving a contemporary voice to diverse perspectives of Islam.\n\nValues:\n\nICCNC promotes the core values of social responsibility, conscientiousness and spirituality.\n\nICCNC provides a welcoming environment for all Muslims and members of other communities to learn about Islam.\n\nICCNC follows the Ja’fari School of Islamic thought.\n\nICCNC believes in a compassionate and inclusive interpretation of Islam and respects various Islamic schools of thought.\n\n\nBased on Islamic teachings, ICCNC believes that all human beings are created equal and have inalienable human rights.\n\n\n"

[channel "image"]
url = https://yt3.ggpht.com/ytc/AKedOLQt42OU3dJOlmZvlMy-9aq8bEsijWUN14aWqeHlZQ=s0

