[item]
guid = 1PAqZDjsbnU
title = "Religion and Science 3 Dr Soroush Sep 12 2021 خلاف و وفاق علم و دین دکتر عبدالکریم سروش جلسه سوم"
description = "#عبدالکریم_سروش #دکترسروش #خلاف_و_وفاق_علم_و_دین #مرکز_اسلامی_فرهنگی_شمال_کالیفرنیا\n#ICCNC #DrSoroush \n\nدر سومین نشست از سلسله‌درس‌گفتارهای دکتر سروش درباره خلاف و وفاق علم و دین، به گذشته رفتار عالمان دینی در جهان غرب و نیز دنیای اسلام و ایران در مواجهه با فیلسوفان دین،‌نقبی زده می‌شود. آقای سروش در این نگاه گذرا اندکی از این سرگذشت اندوهبار را با ذکر مثا‌ل‌هایی از چهره هایی چون ملاصدرای شیرازی و تبعیدش به مکانی دور دست یادآور می‌شود.\nهمچنین از گذشته تحولات  و به خصوص برخی نظریات علمی و تاثیری که آنها بر بیرون راندن دین از زندگی و ساخت و ساحت قدرت در عصر مدرن ایفا کردند سخن رفت؛ همانند نظریات گالیله ونوع مواجهه کلیسا با آن و یا دیدگاه و نظریه داروین و تاثیر آن بر نگاه افراد به دین و نقش آن در تاریخ آدمی \nاو همچنین از برخی دیدگاه‌های خداناباورانی چون ریچارد داوکینز یادکرد که قرار است در جلسات آینده بحث مبسوط‌تری را در این زمینه در همین سلسله جلسات یاد‌آور شود.\nهمچنین معرفی کتاب توهم خدای داوکینز و یکی دو تن دیگر از خداناباوران و نیز خداباوران در این زمینه از جمله مباحث انتهایی نشست سوم بود.\nwww.iccnc.org\n\n https://twitter.com/ICCNC\n\n https://www.instagram.com/iccncofficial\n\nhttps://t.me/Iccnc\n\nhttps://www.facebook.com/ICCNCORG\n\nhttps://www.youtube.com/user/iccnc1\n\nhttps://www.yelp.com/biz/islamic-cultural-center-of-northern-california-oakland-2"
author = info@iccnc.org
source = https://www.youtube.com/channel/UC-wPh48ip_s4P6guKziI7ag
link = https://www.youtube.com/watch?v=1PAqZDjsbnU
category = "Entertainment"
pubdate = Thu, 13 Jan 2022 00:00:00 -0000
enclosure = 1PAqZDjsbnU.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/1PAqZDjsbnU/hqdefault.webp

