[item]
guid = 5__30Re5Krc
title = "Dr Soroush Kimiyaye Saadat 20 گزینش و شرح کیمیای سعادت غزّالی دکتر عبدالکریم سروش، جلسه بیستم"
description = "مخاطبان و پی‌گیران سلسله درس‌گفتارهای دکتر عبدالکریم سروش در گزینش و شرح و نقد کیمیای سعادت امام محمد غزالی اگر در خاطر داشته باشند،‌در نشست نوزدهم آقای سروش موضوع"شناختن حلال و حرام و شبهت "از کتاب حکمی اخلاقی کیمیای سعادت (صفحات ۳۶۶ تا ۳۸۹- جلد نخست)با تصحیح حسین خدیو جم را گزینش و مورد تحلیل قرار داد و از منظر یک تحلیل‌گر موشکاف نقدهای امروزین و باورداشت‌‌های تاریخی نویسنده را به بررسی نشست. آن مبحث اما نیمه‌تمام ماند \nو در این نوبت ادامه آن بحث خواهد آمد\n\nدر مقدمه بحث و پیش از شروع و ادامه مبحث نشست پیشین، آقای سروش به دو رخداد حادث شده در ایران پرداخت، نخست ترور یکی از دانشمندان هسته‌ای و انتقاد از رخنه‌هایی که به سیستم حفاظتی در ایران باید داشت که نتیجه مدیریت ضعیف و برکشاندن به باور او سبک‌مغزان و گذاشتن آنها بر سر امور و کارهای مهم است و دیگری به یاد دکتر محمد ملکی، از مبارزان قبل و بعد از انقلاب.\nدر ادامه آقای سروش به بخش دوم گفتارش درباره اندیشه سیاسی غزالی با توجه به بحث حلال و حرام و با ابتناء‌ به کتاب کیمیای سعادت و نیز اصل این بحث در کتاب احیاء العلوم الدین که ۷ برابر بحث آن در کیمیای سعادت است پرداختند.\nwww.iccnc.org\n\n https://twitter.com/ICCNC\n\n https://www.instagram.com/iccncofficial\n\nhttps://t.me/Iccnc\n\nhttps://www.facebook.com/ICCNCORG\n\nhttps://www.youtube.com/user/iccnc1\n\nhttps://www.yelp.com/biz/islamic-cultural-center-of-northern-california-oakland-2"
author = info@iccnc.org
source = https://www.youtube.com/channel/UC-wPh48ip_s4P6guKziI7ag
link = https://www.youtube.com/watch?v=5__30Re5Krc
category = "Entertainment"
pubdate = Thu, 16 Jun 2022 00:00:00 -0000
enclosure = 5__30Re5Krc.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/5__30Re5Krc/sddefault.webp

