[item]
guid = 7m29t-Z2bF8
title = "ICCNC Friday Prayer by Br. Ahmad Rashid Salim May 27, 2022"
description = "#ICCNC #Ahmad_Sashid_Salim #fridayPrayer #Friday_Prayer #ICCNCFridayPrayer\n\nwww.iccnc.org\n\n https://twitter.com/ICCNC\n\n https://www.instagram.com/iccncofficial\n\nhttps://t.me/Iccnc\n\nhttps://www.facebook.com/ICCNCORG\n\nhttps://www.youtube.com/user/iccnc1\n\nhttps://www.yelp.com/biz/islamic-cultural-center-of-northern-california-oakland-2"
author = info@iccnc.org
source = https://www.youtube.com/channel/UC-wPh48ip_s4P6guKziI7ag
link = https://www.youtube.com/watch?v=7m29t-Z2bF8
category = "Entertainment"
pubdate = Sat, 28 May 2022 00:00:00 -0000
enclosure = 7m29t-Z2bF8.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/7m29t-Z2bF8/hqdefault.jpg

