[item]
guid = DxNOdMCPBzs
title = "Science & Religion  5 Dr Soroush Dec 12 2021 خلاف و وفاق علم و دین دکتر عبدالکریم سروش جلسه پنجم"
description = "#عبدالکریم_سروش #دکترسروش #خلاف_و_وفاق_علم_و_دین #مرکز_اسلامی_فرهنگی_شمال_کالیفرنیا\n#ICCNC #DrSoroush \nدر نشست پنجم از درس‌گفتار خلاف و وفاق علم و دین ، ابتدا سه نوع نگاه در تاریخ مورد اشاره قرار گرفت؛ نگاه اسطوره‌ای، نگاه متافیزیکی و نگاه پوزیتویستی\nسپس به دین پرداخته شد و مواجه علم با دین در دو سطح درون دینی و برون دینی مورد تحلیل قرار گرفت و اشاراتی به خلاف و وفاق این دو در این دو عرصه بیان شد.\nدر ابتدای نشست نیز دکتر سروش به ایام فاطمیه اشاره کردند و خرافات و سخنان ناراستی که از زبان برخی مداحان در این ایام منتشر می‌شود و سپس از طرفین، شیعه وسنی خواست که چنین دعواهایی را فرو بنهند.\nچرا که اسباب فرسودگی توان دو گروه شیعه وسنی می‌شود و آنها را از امور اساسی باز می‌دارد.\nwww.iccnc.org\n\n https://twitter.com/ICCNC\n\n https://www.instagram.com/iccncofficial\n\nhttps://t.me/Iccnc\n\nhttps://www.facebook.com/ICCNCORG\n\nhttps://www.youtube.com/user/iccnc1\n\nhttps://www.yelp.com/biz/islamic-cultural-center-of-northern-california-oakland-2"
author = info@iccnc.org
source = https://www.youtube.com/channel/UC-wPh48ip_s4P6guKziI7ag
link = https://www.youtube.com/watch?v=DxNOdMCPBzs
category = "Entertainment"
pubdate = Sun, 30 Jan 2022 00:00:00 -0000
enclosure = DxNOdMCPBzs.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/DxNOdMCPBzs/sddefault.webp

