[item]
guid = ejqbOJ3DKpU
title = ""Religion and Science" Lecture Series in Farsi by Dr. Soroush 2022-07-24 14:24"
description = "www.iccnc.org\n\n https://twitter.com/ICCNC\n\n https://www.instagram.com/iccncofficial\n\nhttps://t.me/Iccnc\n\nhttps://www.facebook.com/ICCNCORG\n\nhttps://www.youtube.com/user/iccnc1\n\nhttps://www.yelp.com/biz/islamic-cultural-center-of-northern-california-oakland-2"
author = info@iccnc.org
source = https://www.youtube.com/channel/UC-wPh48ip_s4P6guKziI7ag
link = https://www.youtube.com/watch?v=ejqbOJ3DKpU
category = "Entertainment"
pubdate = Sun, 24 Jul 2022 00:00:00 -0000
enclosure = ejqbOJ3DKpU.mp4

[item "itunes"]
image = https://i.ytimg.com/vi/ejqbOJ3DKpU/maxresdefault_live.jpg

