[item]
guid = HDmsI28yZQI
title = "ICCNC Friday Prayer"
description = "www.iccnc.org\n\n https://twitter.com/ICCNC\n\n https://www.instagram.com/iccncofficial\n\nhttps://t.me/Iccnc\n\nhttps://www.facebook.com/ICCNCORG\n\nhttps://www.youtube.com/user/iccnc1\n\nhttps://www.yelp.com/biz/islamic-cultural-center-of-northern-california-oakland-2"
author = info@iccnc.org
source = https://www.youtube.com/channel/UC-wPh48ip_s4P6guKziI7ag
link = https://www.youtube.com/watch?v=HDmsI28yZQI
category = "Entertainment"
pubdate = Sat, 16 Jul 2022 00:00:00 -0000
enclosure = HDmsI28yZQI.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/HDmsI28yZQI/hqdefault.jpg

