[item]
guid = iP_m_y5aB8Q
title = "Science & Religion 7 Dr Soroush Jan  23 2021 خلاف و وفاق علم و دین دکتر عبدالکریم سروش جلسه هفتم"
description = "#عبدالکریم_سروش #دکترسروش #خلاف_و_وفاق_علم_و_دین #مرکز_اسلامی_فرهنگی_شمال_کالیفرنیا\n#ICCNC #DrSoroush \n\nدر هفتمین نشست از درس‌گفتار خلاف و وفاق علم و دین، دکتر عبدالکریم سروش ابتدا سخنانی انتقادی درباره تعلیق دو استاد  دانشگاه‌های ایران از سوی نهادهای دولتی مسئول بیان کردند که اخیرا رخ داده بود که یکی از آن استادان در حوزه فلسفه علم دانشگاه صنعتی شریف تدریس می‌کردند.\nدر ادامه به تئوری‌های علمی پرداخت و این که آیا آنها تئوری‌های یقینی‌اند و یا ظنی که در کل گفتند ما هیچ چیز صد در صد یقینی نداریم و عمده امور ظنی‌ هستند و برخی ظن به یقنشان نزدیک‌تر است  و  وگرنه امر یا تئوری صد درصد یقنیی نداریم.\n\nایشان سپس به نظریه احتمالات پرداخت و این پرسش را مطرح ساخت که معيار احتمال چیست و آیا آن یک امر ذهنی است یا عینی و در ادامه به بقیه استنتاجات فلسفی از جمله استقراء و رابطه آن با فلسفه علم پرداخت. \nwww.iccnc.org\n\n https://twitter.com/ICCNC\n\n https://www.instagram.com/iccncofficial\n\nhttps://t.me/Iccnc\n\nhttps://www.facebook.com/ICCNCORG\n\nhttps://www.youtube.com/user/iccnc1\n\nhttps://www.yelp.com/biz/islamic-cultural-center-of-northern-california-oakland-2"
author = info@iccnc.org
source = https://www.youtube.com/channel/UC-wPh48ip_s4P6guKziI7ag
link = https://www.youtube.com/watch?v=iP_m_y5aB8Q
category = "Entertainment"
pubdate = Mon, 14 Mar 2022 00:00:00 -0000
enclosure = iP_m_y5aB8Q.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/iP_m_y5aB8Q/sddefault.webp

