[item]
guid = LLVeXfd7pm0
title = "Science & Religion 9 Dr Soroush Feb 20 2021 خلاف و وفاق علم و دین دکتر عبدالکریم سروش جلسه نهم"
description = "در نهمین نشست از درس‌گفتار خلاف و وفاق علم و دین، تمرکز دکتر عبدالکریم سروش بر تشریح مفهومی به نام ماده است که با تبارشناسی‌ای تاریخی از تحولات ماده با تاکید بر علم فیزیک به دوره کنونی و دنیای کوانتم می‌آید و سپس این تحول را با نظریات شیخ‌شهاب‌الدین سهروردی در می آمیزد و نتیجه می‌گیرد که می‌توان به این فهم رسید که یک مدبری دارد و نفس مدبری که جهان را مدیریت می‌کند.\nwww.iccnc.org\n\n https://twitter.com/ICCNC\n\n https://www.instagram.com/iccncofficial\n\nhttps://t.me/Iccnc\n\nhttps://www.facebook.com/ICCNCORG\n\nhttps://www.youtube.com/user/iccnc1\n\nhttps://www.yelp.com/biz/islamic-cultural-center-of-northern-california-oakland-2"
author = info@iccnc.org
source = https://www.youtube.com/channel/UC-wPh48ip_s4P6guKziI7ag
link = https://www.youtube.com/watch?v=LLVeXfd7pm0
category = "Entertainment"
pubdate = Tue, 19 Apr 2022 00:00:00 -0000
enclosure = LLVeXfd7pm0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/LLVeXfd7pm0/hqdefault.jpg

