[item]
guid = M9qF_hoaJSI
title = "Dr Soroush Mathnawi 6 Episode 3:: شرح دفتر ششم مثنوی از سوی دکتر عبدالکریم سروش، جلسه سوم"
description = "دکتر#عبدالکریم__سروش    #دکتر_سروش  #شرح_دفتر_ششم_مثنوی  #دفتر_ششم_مثنوی  #مرکز_اسلامی_فرهنگی_شمال_کالیفرنیا  ا \n#DrSoroush Dr.#Abdolkarim_Soroush #iccnc #Mathnawi #rumi \n-----------------------------------------------------------------------------------------------------\nدر سومین نشست از شرح دفتر ششم مثنوی و پیش از بحث اصلی نشست، دکتر سروش به مناسبت درگذشت دکتر محمدرضا حکیمی نکاتی را درباره‌ آن زنده‌یاد و منش فکری و آثاری که تالیف کردند بیان داشتند و سپس درس مثنوی رااز بیت ۹۰ آغاز کردند:\nچون زمین زین برف در پوشد کفن\nتیغ خورشید حسام‌الدین بزن\nو سپس بعد از توضیحات درباره ابیات بعدی نشست را در بیت ۱۲۰ از همین دفتر به پایان می‌رسانند. ابیاتی که نشان می‌دهد هنوز مولانا در مقدمات سخن می‌گوید و مخاطب او نیز حسام‌الدین است و هنوز وارد داستان خاصی نشده است.\nعقلشان در نقل دنیا پیچ پیچ\nفکرشان در ترک شهوت هیچ هیچ \nwww.iccnc.org\n\n https://twitter.com/ICCNC\n\n https://www.instagram.com/iccncofficial\n\nhttps://t.me/Iccnc\n\nhttps://www.facebook.com/ICCNCORG\n\nhttps://www.youtube.com/user/iccnc1\n\nhttps://www.yelp.com/biz/islamic-cultural-center-of-northern-california-oakland-2"
author = info@iccnc.org
source = https://www.youtube.com/channel/UC-wPh48ip_s4P6guKziI7ag
link = https://www.youtube.com/watch?v=M9qF_hoaJSI
category = "Entertainment"
pubdate = Thu, 21 Jul 2022 00:00:00 -0000
enclosure = M9qF_hoaJSI.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/M9qF_hoaJSI/hqdefault.jpg

