[item]
guid = PLUNUX71JYY
title = "Dr Soroush Mathnawi 6 Episode 2 :شرح دفتر ششم مثنوی از سوی دکتر عبدالکریم سروش، جلسه دوم ت"
description = "در نشست و جلسه دوم از شرح دفتر ششم مثنوی مولانا همچنان در مقدمات صحبت می‌کند و نشست از بیت چهلم شروع می‌شود:\nذره‌ای کآن محو شد در آفتاب\nجنگ او بیرون شد از وصف و حساب\nسپس در ادامه نیز بحثی درباره خودشناسی و این که آدمی اول باید در خود نظر کند و در پایان نیز با بیت زیر که هشتاد و هشتمین بیت از دفتر ششم مثنوی است درس به پایان می‌رسد\nبو نگهدار و بپرهیز از زکام\nتن بپوش از باد و بود سرد عام\nدر بخش پرسش و پاسخ نیز دکتر سروش ضمن اشاره به کتاب‌هایی که درباره زندگی مولانا نوشته شده‌اند به اثر دکتر بدیع‌الزمان فروزانفر و نیز عبدالباقی گولپینارلی(با ترجمه دکتر توفیق سبحانی) اشاره کرده ونیز از کتاب پله پله تا ملاقات خدای دکتر عبدالحسین زرین‌کوب هم به عنوان اثری خواندنی یاد می‌کند.\nایشان همچنین درباره ماجرای کیمیاخاتون و شمس و فرزند مولانا نکاتی را به نقل ازپژوهش‌های دکتر موحد و نیز کتاب مقالات شمس بیان می‌کند که  ه \n\nwww.iccnc.org\n\n https://twitter.com/ICCNC\n\n https://www.instagram.com/iccncofficial\n\nhttps://t.me/Iccnc\n\nhttps://www.facebook.com/ICCNCORG\n\nhttps://www.youtube.com/user/iccnc1\n\nhttps://www.yelp.com/biz/islamic-cultural-center-of-northern-california-oakland-2"
author = info@iccnc.org
source = https://www.youtube.com/channel/UC-wPh48ip_s4P6guKziI7ag
link = https://www.youtube.com/watch?v=PLUNUX71JYY
category = "Entertainment"
pubdate = Fri, 15 Jul 2022 00:00:00 -0000
enclosure = PLUNUX71JYY.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/PLUNUX71JYY/hqdefault.jpg

