[item]
guid = sokVWW2FtxQ
title = "Science & Religion 8 Dr Soroush Feb 6 2021 خلاف و وفاق علم و دین دکتر عبدالکریم سروش جلسه هشتم"
description = "#عبدالکریم_سروش #دکترسروش #خلاف_و_وفاق_علم_و_دین #مرکز_اسلامی_فرهنگی_شمال_کالیفرنیا\n#ICCNC #DrSoroush \n\nwww.iccnc.org\n\n https://twitter.com/ICCNC\n\n https://www.instagram.com/iccncofficial\n\nhttps://t.me/Iccnc\n\nhttps://www.facebook.com/ICCNCORG\n\nhttps://www.youtube.com/user/iccnc1\n\nhttps://www.yelp.com/biz/islamic-cultural-center-of-northern-california-oakland-2"
author = info@iccnc.org
source = https://www.youtube.com/channel/UC-wPh48ip_s4P6guKziI7ag
link = https://www.youtube.com/watch?v=sokVWW2FtxQ
category = "Entertainment"
pubdate = Sat, 02 Apr 2022 00:00:00 -0000
enclosure = sokVWW2FtxQ.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/sokVWW2FtxQ/sddefault.webp

