[item]
guid = w2vWM5QAios
title = "ICCNC Friday Prayer"
description = "www.iccnc.org\n\n https://twitter.com/ICCNC\n\n https://www.instagram.com/iccncofficial\n\nhttps://t.me/Iccnc\n\nhttps://www.facebook.com/ICCNCORG\n\nhttps://www.youtube.com/user/iccnc1\n\nhttps://www.yelp.com/biz/islamic-cultural-center-of-northern-california-oakland-2"
author = info@iccnc.org
source = https://www.youtube.com/channel/UC-wPh48ip_s4P6guKziI7ag
link = https://www.youtube.com/watch?v=w2vWM5QAios
category = "Entertainment"
pubdate = Fri, 29 Jul 2022 00:00:00 -0000
enclosure = w2vWM5QAios.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/w2vWM5QAios/maxresdefault_live.jpg

