[item]
guid = wBVuZGD3QgQ
title = "Dr Soroush Kimiyaye Saadat 21 گزینش و شرح کیمیای سعادت غزّالی دکتر عبدالکریم سروش، جلسه بیست و یکم"
description = "www.iccnc.org\n\n https://twitter.com/ICCNC\n\n https://www.instagram.com/iccncofficial\n\nhttps://t.me/Iccnc\n\nhttps://www.facebook.com/ICCNCORG\n\nhttps://www.youtube.com/user/iccnc1\n\nhttps://www.yelp.com/biz/islamic-cultural-center-of-northern-california-oakland-2"
author = info@iccnc.org
source = https://www.youtube.com/channel/UC-wPh48ip_s4P6guKziI7ag
link = https://www.youtube.com/watch?v=wBVuZGD3QgQ
category = "Entertainment"
pubdate = Thu, 23 Jun 2022 00:00:00 -0000
enclosure = wBVuZGD3QgQ.mp4

[item "itunes"]
image = https://i.ytimg.com/vi/wBVuZGD3QgQ/maxresdefault.jpg

