[item]
guid = xoVZ5UP2X4c
title = "ICCNC Friday Prayer 2022-06-17 16:27"
description = "www.iccnc.org\n\n https://twitter.com/ICCNC\n\n https://www.instagram.com/iccncofficial\n\nhttps://t.me/Iccnc\n\nhttps://www.facebook.com/ICCNCORG\n\nhttps://www.youtube.com/user/iccnc1\n\nhttps://www.yelp.com/biz/islamic-cultural-center-of-northern-california-oakland-2"
author = info@iccnc.org
source = https://www.youtube.com/channel/UC-wPh48ip_s4P6guKziI7ag
link = https://www.youtube.com/watch?v=xoVZ5UP2X4c
category = "Entertainment"
pubdate = Fri, 17 Jun 2022 00:00:00 -0000
enclosure = xoVZ5UP2X4c.mp4

[item "itunes"]
image = https://i.ytimg.com/vi/xoVZ5UP2X4c/maxresdefault_live.jpg

